// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	http "net/http"

	mock "github.com/stretchr/testify/mock"

	models "github.com/DmitriySama/teammate_search/internal/models"

	pgstorage "github.com/DmitriySama/teammate_search/internal/storage/pgstorage"

	sql "database/sql"
)

// MockUsersStorage is an autogenerated mock type for the UsersStorage type
type MockUsersStorage struct {
	mock.Mock
}

type MockUsersStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsersStorage) EXPECT() *MockUsersStorage_Expecter {
	return &MockUsersStorage_Expecter{mock: &_m.Mock}
}

// FindUser provides a mock function with given fields: username, password
func (_m *MockUsersStorage) FindUser(username string, password string) (int, error) {
	ret := _m.Called(username, password)

	if len(ret) == 0 {
		panic("no return value specified for FindUser")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (int, error)); ok {
		return rf(username, password)
	}
	if rf, ok := ret.Get(0).(func(string, string) int); ok {
		r0 = rf(username, password)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(username, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsersStorage_FindUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUser'
type MockUsersStorage_FindUser_Call struct {
	*mock.Call
}

// FindUser is a helper method to define mock.On call
//   - username string
//   - password string
func (_e *MockUsersStorage_Expecter) FindUser(username interface{}, password interface{}) *MockUsersStorage_FindUser_Call {
	return &MockUsersStorage_FindUser_Call{Call: _e.mock.On("FindUser", username, password)}
}

func (_c *MockUsersStorage_FindUser_Call) Run(run func(username string, password string)) *MockUsersStorage_FindUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockUsersStorage_FindUser_Call) Return(_a0 int, _a1 error) *MockUsersStorage_FindUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsersStorage_FindUser_Call) RunAndReturn(run func(string, string) (int, error)) *MockUsersStorage_FindUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetApps provides a mock function with given fields: ctx
func (_m *MockUsersStorage) GetApps(ctx context.Context) ([]models.Apps, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetApps")
	}

	var r0 []models.Apps
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.Apps, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.Apps); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Apps)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsersStorage_GetApps_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApps'
type MockUsersStorage_GetApps_Call struct {
	*mock.Call
}

// GetApps is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUsersStorage_Expecter) GetApps(ctx interface{}) *MockUsersStorage_GetApps_Call {
	return &MockUsersStorage_GetApps_Call{Call: _e.mock.On("GetApps", ctx)}
}

func (_c *MockUsersStorage_GetApps_Call) Run(run func(ctx context.Context)) *MockUsersStorage_GetApps_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockUsersStorage_GetApps_Call) Return(_a0 []models.Apps, _a1 error) *MockUsersStorage_GetApps_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsersStorage_GetApps_Call) RunAndReturn(run func(context.Context) ([]models.Apps, error)) *MockUsersStorage_GetApps_Call {
	_c.Call.Return(run)
	return _c
}

// GetGames provides a mock function with given fields: ctx
func (_m *MockUsersStorage) GetGames(ctx context.Context) ([]models.Games, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetGames")
	}

	var r0 []models.Games
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.Games, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.Games); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Games)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsersStorage_GetGames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGames'
type MockUsersStorage_GetGames_Call struct {
	*mock.Call
}

// GetGames is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUsersStorage_Expecter) GetGames(ctx interface{}) *MockUsersStorage_GetGames_Call {
	return &MockUsersStorage_GetGames_Call{Call: _e.mock.On("GetGames", ctx)}
}

func (_c *MockUsersStorage_GetGames_Call) Run(run func(ctx context.Context)) *MockUsersStorage_GetGames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockUsersStorage_GetGames_Call) Return(_a0 []models.Games, _a1 error) *MockUsersStorage_GetGames_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsersStorage_GetGames_Call) RunAndReturn(run func(context.Context) ([]models.Games, error)) *MockUsersStorage_GetGames_Call {
	_c.Call.Return(run)
	return _c
}

// GetGenres provides a mock function with given fields: ctx
func (_m *MockUsersStorage) GetGenres(ctx context.Context) ([]models.Genres, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetGenres")
	}

	var r0 []models.Genres
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.Genres, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.Genres); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Genres)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsersStorage_GetGenres_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGenres'
type MockUsersStorage_GetGenres_Call struct {
	*mock.Call
}

// GetGenres is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUsersStorage_Expecter) GetGenres(ctx interface{}) *MockUsersStorage_GetGenres_Call {
	return &MockUsersStorage_GetGenres_Call{Call: _e.mock.On("GetGenres", ctx)}
}

func (_c *MockUsersStorage_GetGenres_Call) Run(run func(ctx context.Context)) *MockUsersStorage_GetGenres_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockUsersStorage_GetGenres_Call) Return(_a0 []models.Genres, _a1 error) *MockUsersStorage_GetGenres_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsersStorage_GetGenres_Call) RunAndReturn(run func(context.Context) ([]models.Genres, error)) *MockUsersStorage_GetGenres_Call {
	_c.Call.Return(run)
	return _c
}

// GetLanguages provides a mock function with given fields: ctx
func (_m *MockUsersStorage) GetLanguages(ctx context.Context) ([]models.Language, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLanguages")
	}

	var r0 []models.Language
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.Language, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.Language); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Language)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsersStorage_GetLanguages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLanguages'
type MockUsersStorage_GetLanguages_Call struct {
	*mock.Call
}

// GetLanguages is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUsersStorage_Expecter) GetLanguages(ctx interface{}) *MockUsersStorage_GetLanguages_Call {
	return &MockUsersStorage_GetLanguages_Call{Call: _e.mock.On("GetLanguages", ctx)}
}

func (_c *MockUsersStorage_GetLanguages_Call) Run(run func(ctx context.Context)) *MockUsersStorage_GetLanguages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockUsersStorage_GetLanguages_Call) Return(_a0 []models.Language, _a1 error) *MockUsersStorage_GetLanguages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsersStorage_GetLanguages_Call) RunAndReturn(run func(context.Context) ([]models.Language, error)) *MockUsersStorage_GetLanguages_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function with given fields: userID
func (_m *MockUsersStorage) GetUserByID(userID int) (*models.User, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*models.User, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(int) *models.User); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsersStorage_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockUsersStorage_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - userID int
func (_e *MockUsersStorage_Expecter) GetUserByID(userID interface{}) *MockUsersStorage_GetUserByID_Call {
	return &MockUsersStorage_GetUserByID_Call{Call: _e.mock.On("GetUserByID", userID)}
}

func (_c *MockUsersStorage_GetUserByID_Call) Run(run func(userID int)) *MockUsersStorage_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockUsersStorage_GetUserByID_Call) Return(_a0 *models.User, _a1 error) *MockUsersStorage_GetUserByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsersStorage_GetUserByID_Call) RunAndReturn(run func(int) (*models.User, error)) *MockUsersStorage_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserCount provides a mock function with no fields
func (_m *MockUsersStorage) GetUserCount() (int, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUserCount")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func() (int, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsersStorage_GetUserCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserCount'
type MockUsersStorage_GetUserCount_Call struct {
	*mock.Call
}

// GetUserCount is a helper method to define mock.On call
func (_e *MockUsersStorage_Expecter) GetUserCount() *MockUsersStorage_GetUserCount_Call {
	return &MockUsersStorage_GetUserCount_Call{Call: _e.mock.On("GetUserCount")}
}

func (_c *MockUsersStorage_GetUserCount_Call) Run(run func()) *MockUsersStorage_GetUserCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUsersStorage_GetUserCount_Call) Return(_a0 int, _a1 error) *MockUsersStorage_GetUserCount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsersStorage_GetUserCount_Call) RunAndReturn(run func() (int, error)) *MockUsersStorage_GetUserCount_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsers provides a mock function with given fields: r
func (_m *MockUsersStorage) GetUsers(r *http.Request) (*sql.Rows, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 *sql.Rows
	var r1 error
	if rf, ok := ret.Get(0).(func(*http.Request) (*sql.Rows, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(*http.Request) *sql.Rows); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Rows)
		}
	}

	if rf, ok := ret.Get(1).(func(*http.Request) error); ok {
		r1 = rf(r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsersStorage_GetUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsers'
type MockUsersStorage_GetUsers_Call struct {
	*mock.Call
}

// GetUsers is a helper method to define mock.On call
//   - r *http.Request
func (_e *MockUsersStorage_Expecter) GetUsers(r interface{}) *MockUsersStorage_GetUsers_Call {
	return &MockUsersStorage_GetUsers_Call{Call: _e.mock.On("GetUsers", r)}
}

func (_c *MockUsersStorage_GetUsers_Call) Run(run func(r *http.Request)) *MockUsersStorage_GetUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*http.Request))
	})
	return _c
}

func (_c *MockUsersStorage_GetUsers_Call) Return(_a0 *sql.Rows, _a1 error) *MockUsersStorage_GetUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsersStorage_GetUsers_Call) RunAndReturn(run func(*http.Request) (*sql.Rows, error)) *MockUsersStorage_GetUsers_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: username, password
func (_m *MockUsersStorage) Login(username string, password string) (*pgstorage.AuthResult, error) {
	ret := _m.Called(username, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *pgstorage.AuthResult
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*pgstorage.AuthResult, error)); ok {
		return rf(username, password)
	}
	if rf, ok := ret.Get(0).(func(string, string) *pgstorage.AuthResult); ok {
		r0 = rf(username, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pgstorage.AuthResult)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(username, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsersStorage_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockUsersStorage_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - username string
//   - password string
func (_e *MockUsersStorage_Expecter) Login(username interface{}, password interface{}) *MockUsersStorage_Login_Call {
	return &MockUsersStorage_Login_Call{Call: _e.mock.On("Login", username, password)}
}

func (_c *MockUsersStorage_Login_Call) Run(run func(username string, password string)) *MockUsersStorage_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockUsersStorage_Login_Call) Return(_a0 *pgstorage.AuthResult, _a1 error) *MockUsersStorage_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsersStorage_Login_Call) RunAndReturn(run func(string, string) (*pgstorage.AuthResult, error)) *MockUsersStorage_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: username, password, description, age
func (_m *MockUsersStorage) Register(username string, password string, description string, age int) (*pgstorage.AuthResult, error) {
	ret := _m.Called(username, password, description, age)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *pgstorage.AuthResult
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string, int) (*pgstorage.AuthResult, error)); ok {
		return rf(username, password, description, age)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, int) *pgstorage.AuthResult); ok {
		r0 = rf(username, password, description, age)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pgstorage.AuthResult)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string, int) error); ok {
		r1 = rf(username, password, description, age)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsersStorage_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockUsersStorage_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - username string
//   - password string
//   - description string
//   - age int
func (_e *MockUsersStorage_Expecter) Register(username interface{}, password interface{}, description interface{}, age interface{}) *MockUsersStorage_Register_Call {
	return &MockUsersStorage_Register_Call{Call: _e.mock.On("Register", username, password, description, age)}
}

func (_c *MockUsersStorage_Register_Call) Run(run func(username string, password string, description string, age int)) *MockUsersStorage_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string), args[3].(int))
	})
	return _c
}

func (_c *MockUsersStorage_Register_Call) Return(_a0 *pgstorage.AuthResult, _a1 error) *MockUsersStorage_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsersStorage_Register_Call) RunAndReturn(run func(string, string, string, int) (*pgstorage.AuthResult, error)) *MockUsersStorage_Register_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function with given fields: r, user
func (_m *MockUsersStorage) UpdateUser(r *http.Request, user models.User) error {
	ret := _m.Called(r, user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*http.Request, models.User) error); ok {
		r0 = rf(r, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUsersStorage_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockUsersStorage_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - r *http.Request
//   - user models.User
func (_e *MockUsersStorage_Expecter) UpdateUser(r interface{}, user interface{}) *MockUsersStorage_UpdateUser_Call {
	return &MockUsersStorage_UpdateUser_Call{Call: _e.mock.On("UpdateUser", r, user)}
}

func (_c *MockUsersStorage_UpdateUser_Call) Run(run func(r *http.Request, user models.User)) *MockUsersStorage_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*http.Request), args[1].(models.User))
	})
	return _c
}

func (_c *MockUsersStorage_UpdateUser_Call) Return(_a0 error) *MockUsersStorage_UpdateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUsersStorage_UpdateUser_Call) RunAndReturn(run func(*http.Request, models.User) error) *MockUsersStorage_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// UserExists provides a mock function with given fields: username
func (_m *MockUsersStorage) UserExists(username string) (bool, error) {
	ret := _m.Called(username)

	if len(ret) == 0 {
		panic("no return value specified for UserExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return rf(username)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(username)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsersStorage_UserExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserExists'
type MockUsersStorage_UserExists_Call struct {
	*mock.Call
}

// UserExists is a helper method to define mock.On call
//   - username string
func (_e *MockUsersStorage_Expecter) UserExists(username interface{}) *MockUsersStorage_UserExists_Call {
	return &MockUsersStorage_UserExists_Call{Call: _e.mock.On("UserExists", username)}
}

func (_c *MockUsersStorage_UserExists_Call) Run(run func(username string)) *MockUsersStorage_UserExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockUsersStorage_UserExists_Call) Return(_a0 bool, _a1 error) *MockUsersStorage_UserExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsersStorage_UserExists_Call) RunAndReturn(run func(string) (bool, error)) *MockUsersStorage_UserExists_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUsersStorage creates a new instance of MockUsersStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsersStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsersStorage {
	mock := &MockUsersStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
