// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/DmitriySama/teammate_search/internal/models"
)

// MockTasksCache is an autogenerated mock type for the TasksCache type
type MockTasksCache struct {
	mock.Mock
}

type MockTasksCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTasksCache) EXPECT() *MockTasksCache_Expecter {
	return &MockTasksCache_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, orderID, groupID
func (_m *MockTasksCache) Get(ctx context.Context, orderID string, groupID string) ([]models.User, string, bool) {
	ret := _m.Called(ctx, orderID, groupID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []models.User
	var r1 string
	var r2 bool
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]models.User, string, bool)); ok {
		return rf(ctx, orderID, groupID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []models.User); ok {
		r0 = rf(ctx, orderID, groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) string); ok {
		r1 = rf(ctx, orderID, groupID)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) bool); ok {
		r2 = rf(ctx, orderID, groupID)
	} else {
		r2 = ret.Get(2).(bool)
	}

	return r0, r1, r2
}

// MockTasksCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockTasksCache_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
//   - groupID string
func (_e *MockTasksCache_Expecter) Get(ctx interface{}, orderID interface{}, groupID interface{}) *MockTasksCache_Get_Call {
	return &MockTasksCache_Get_Call{Call: _e.mock.On("Get", ctx, orderID, groupID)}
}

func (_c *MockTasksCache_Get_Call) Run(run func(ctx context.Context, orderID string, groupID string)) *MockTasksCache_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTasksCache_Get_Call) Return(_a0 []models.User, _a1 string, _a2 bool) *MockTasksCache_Get_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockTasksCache_Get_Call) RunAndReturn(run func(context.Context, string, string) ([]models.User, string, bool)) *MockTasksCache_Get_Call {
	_c.Call.Return(run)
	return _c
}

// InvalidateGroup provides a mock function with given fields: ctx, orderID, groupID
func (_m *MockTasksCache) InvalidateGroup(ctx context.Context, orderID string, groupID string) {
	_m.Called(ctx, orderID, groupID)
}

// MockTasksCache_InvalidateGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvalidateGroup'
type MockTasksCache_InvalidateGroup_Call struct {
	*mock.Call
}

// InvalidateGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
//   - groupID string
func (_e *MockTasksCache_Expecter) InvalidateGroup(ctx interface{}, orderID interface{}, groupID interface{}) *MockTasksCache_InvalidateGroup_Call {
	return &MockTasksCache_InvalidateGroup_Call{Call: _e.mock.On("InvalidateGroup", ctx, orderID, groupID)}
}

func (_c *MockTasksCache_InvalidateGroup_Call) Run(run func(ctx context.Context, orderID string, groupID string)) *MockTasksCache_InvalidateGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTasksCache_InvalidateGroup_Call) Return() *MockTasksCache_InvalidateGroup_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTasksCache_InvalidateGroup_Call) RunAndReturn(run func(context.Context, string, string)) *MockTasksCache_InvalidateGroup_Call {
	_c.Run(run)
	return _c
}

// InvalidateOrder provides a mock function with given fields: ctx, orderID
func (_m *MockTasksCache) InvalidateOrder(ctx context.Context, orderID string) {
	_m.Called(ctx, orderID)
}

// MockTasksCache_InvalidateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvalidateOrder'
type MockTasksCache_InvalidateOrder_Call struct {
	*mock.Call
}

// InvalidateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
func (_e *MockTasksCache_Expecter) InvalidateOrder(ctx interface{}, orderID interface{}) *MockTasksCache_InvalidateOrder_Call {
	return &MockTasksCache_InvalidateOrder_Call{Call: _e.mock.On("InvalidateOrder", ctx, orderID)}
}

func (_c *MockTasksCache_InvalidateOrder_Call) Run(run func(ctx context.Context, orderID string)) *MockTasksCache_InvalidateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTasksCache_InvalidateOrder_Call) Return() *MockTasksCache_InvalidateOrder_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTasksCache_InvalidateOrder_Call) RunAndReturn(run func(context.Context, string)) *MockTasksCache_InvalidateOrder_Call {
	_c.Run(run)
	return _c
}

// Set provides a mock function with given fields: ctx, orderID, groupID, groupName, tasks
func (_m *MockTasksCache) Set(ctx context.Context, orderID string, groupID string, groupName string, tasks []models.User) {
	_m.Called(ctx, orderID, groupID, groupName, tasks)
}

// MockTasksCache_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockTasksCache_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
//   - groupID string
//   - groupName string
//   - tasks []models.Task
func (_e *MockTasksCache_Expecter) Set(ctx interface{}, orderID interface{}, groupID interface{}, groupName interface{}, tasks interface{}) *MockTasksCache_Set_Call {
	return &MockTasksCache_Set_Call{Call: _e.mock.On("Set", ctx, orderID, groupID, groupName, tasks)}
}

func (_c *MockTasksCache_Set_Call) Run(run func(ctx context.Context, orderID string, groupID string, groupName string, tasks []models.User)) *MockTasksCache_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].([]models.User))
	})
	return _c
}

func (_c *MockTasksCache_Set_Call) Return() *MockTasksCache_Set_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTasksCache_Set_Call) RunAndReturn(run func(context.Context, string, string, string, []models.User)) *MockTasksCache_Set_Call {
	_c.Run(run)
	return _c
}

// UpdateTaskInCache provides a mock function with given fields: ctx, orderID, groupID, taskID, status
func (_m *MockTasksCache) UpdateTaskInCache(ctx context.Context, orderID string, groupID string, taskID int64, status string) {
	_m.Called(ctx, orderID, groupID, taskID, status)
}

// MockTasksCache_UpdateTaskInCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTaskInCache'
type MockTasksCache_UpdateTaskInCache_Call struct {
	*mock.Call
}

// UpdateTaskInCache is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
//   - groupID string
//   - taskID int64
//   - status string
func (_e *MockTasksCache_Expecter) UpdateTaskInCache(ctx interface{}, orderID interface{}, groupID interface{}, taskID interface{}, status interface{}) *MockTasksCache_UpdateTaskInCache_Call {
	return &MockTasksCache_UpdateTaskInCache_Call{Call: _e.mock.On("UpdateTaskInCache", ctx, orderID, groupID, taskID, status)}
}

func (_c *MockTasksCache_UpdateTaskInCache_Call) Run(run func(ctx context.Context, orderID string, groupID string, taskID int64, status string)) *MockTasksCache_UpdateTaskInCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int64), args[4].(string))
	})
	return _c
}

func (_c *MockTasksCache_UpdateTaskInCache_Call) Return() *MockTasksCache_UpdateTaskInCache_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTasksCache_UpdateTaskInCache_Call) RunAndReturn(run func(context.Context, string, string, int64, string)) *MockTasksCache_UpdateTaskInCache_Call {
	_c.Run(run)
	return _c
}

// NewMockTasksCache creates a new instance of MockTasksCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTasksCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTasksCache {
	mock := &MockTasksCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
